### ISSUE TITLE
People cant connect to NHM servers

### ISSUE THREAD

**Issue by stevo63** [DillonN/NiceHashMiner#16]
https://www.reddit.com/r/NiceHash/comments/6iw67g/screenshot_cannot_connect_to_any_servers_anyone/

**Comment by DillonN** [comment]
Yes, this is a NiceHash server side problem (out of my control)

For now try mining on the a different server, right now the USA one is working for me (although it looks in that screenshot, not for everyone)

**Comment by stevo63** [comment]
Thanks for info. I wasn't sure where problem was.

**Comment by ydem** [comment]
DillonN i think i know what's causing it, not all benchmark do, but only EWBF (and maybe a couple claymore you added) that does it for me, and since the official NHM don't have them, i was wondering if they did add some sort of filtering of any algo that they don't have on their database triggers an ip ban?

I benchmarked in precise mode all the other algos (unticked claymore group since i still have slow hashrate on my gtx 970 with anything related to ethereum), and the moment i reached EWBF it said terminated, then went to start mining and got my ip on EU server banned, i then switched to US servers and started mining, then stopped again and did another benchmark test on EWBF alone, then right afterward the ip got banned on US servers aswell, until i changed ip...

**Comment by ydem** [comment]
`    {
      "Name": "excavator_Equihash",
      "NiceHashID": 24,
      "SecondaryNiceHashID": -1,
      "MinerBaseType": 9,
      "MinerName": "equihash",
      "BenchmarkSpeed": 266.323314,
      "SecondaryBenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": "-ct 4",
      "Enabled": false,
      "LessThreads": 0
    },`

`    {
      "Name": "EWBF_Equihash",
      "NiceHashID": 24,
      "SecondaryNiceHashID": -1,
      "MinerBaseType": 13,
      "MinerName": "",
      "BenchmarkSpeed": 266.323314,
      "SecondaryBenchmarkSpeed": 0.0,
      "ExtraLaunchParameters": "",
      "Enabled": true,
      "LessThreads": 0
    },`

I see on the config file that some of the algos uses the same NiceHashID, could that be conflicting in any way? just trying to throw suggestions from what i noticed...

**Comment by CreamyG31337** [comment]
never seen this until I tried your version...
20:45:51:418	5250	 SC: Stratum - Connected (sia.eu.nicehash.com:3360)
20:45:51:565	5250	got 55 bytes
20:45:51:565	5250	buf: {"id":1,"result":false,"error":[0,"Temp banned",null]}

20:45:51:565	5250	parse packet: 53
20:45:51:565	5250	 SC: Stratum Error: [
   0,
   "Tempbanned",
   null
]
20:45:51:565	5250	new buf size: 0
20:45:51:565	5250	Socket was closed remotely (by pool)
20:45:51:565	5250	 SC: Job timeout, disconnect, retry in 20 sec...

**Comment by CreamyG31337** [comment]
It does kinda seem like the benchmarking was killing it. Everything is working right now, but I tried a whole bunch of times to benchmark the dual miners and it refused to do it. Just shows that it's timing out the connection in the log. The temp ban message is really rare. I have a 1080 and 1080Ti in this machine. It did get through them on the 1080 Ti after a few tries, but the 1080 has so far been unsuccessful. 
Just tried benchmarking ONE random dual miner on it (lbry), and it failed with a bunch of timeouts. Nothing about being banned, but it seems that I am since I closed that and ccminer can't do Lyra2REv2 anymore either, it has the timeout disease. Meanwhile the other GPU and CPU are mining away happily with Lbry and cryptonight.

**Comment by DillonN** [comment]
It does seem like there may be something wrong with NiceHash servers, unfortunately I don't have any info that you guys don't (looks like botched DDoS protection?). I don't believe it has anything to do with my version of NHM since the same errors can pop up when running the miners directly (and NH is supposed to work with any miners that work on other pools). For now if you're running into too many issues you can try using the official NHM, or different server locations. If it doesn't clear up soon I'll look into it more but with miners not working when run directly not sure what I can do

As far as benchmarking goes, (if I recall correctly) EWBF and ClaymoreDual are the only miners that don't have a built in benchmarking mode, and so they temporarily connect to NH for the benchmark. Other benchmarks would be unaffected since their offline benchmark mode would not be troubled by NH servers. The official NHM likely has this issue as well (ClaymoreDual is in the official NHM for AMD cards)

**Comment by ydem** [comment]
Hey DillonN, I like your cooperation to this project but don't understand this non sense in reddit about trying to protect themselves from third party forks such as yours, don't mind the baseless accusations : https://www.reddit.com/r/NiceHash/comments/6izqrc/important_always_download_only_from_official/

**Comment by nonotme1** [comment]
I'm the guy who started the thread on reddit,

Dillion, check the ports in configuration you're putting out. There is an extra 3 I'm most of the ports causing what seems like an attempted Ddos on there end.

Port should be 3354 NOT 33354, etc.

Anyway, the equihash, which is configured correctly, is indeed about 20% faster than the official release.

**Comment by DillonN** [comment]
@ydem there shouldn't be an issue with multiple miners that have the same algo, stock version of NHM has this as well (for AMD). Also EWBF mines equihash which is supported on NH, not sure why they would try to filter it out since they openly support mining with any miner program. Downloading EWBF and manually using it to mine for NH is something they officially support and in essence that's all my version of NHM does

It looks like NH is just warning people of downloading from untrustworthy sources, which is a sensible warning. Obviously my version does not contain any viruses and you're welcome to go through the source code and build it yourself (beauty of open source). I've always warned that this version is unofficial and NH would always prefer you to use the official software since it makes it easier for them to help people

**Comment by DillonN** [comment]
@nonotme1 Which miners do you see an extra 3 in? I'm going through a bunch and do not see that

**Comment by ydem** [comment]
@nonotme1, @DillonN Yeah i know (about compiling the code myself), i was just mentioning it since i found the claim a bit baseless, you can easily see how many watts your card use on both official and fork, and you can see on the official website the average income, so there is no way to siphon money from the system unless you optimized the algo so much that it makes the user more money than the official one, and at the same time an extra part is taken somewhere else, which is non sense and wouldn't mind even if that ever happens to be the case (which isn't).

**Comment by DillonN** [comment]
@ydem thanks for the support, I didn't think you were accusing me of it haha. 

I made a comment on the NH subreddit [here](https://www.reddit.com/r/NiceHash/comments/6izqrc/important_always_download_only_from_official/djak0bx/), I still don't think my NHM is getting people banned but I'd recommend using the official version for the time being until we hear an update.

**Comment by nonotme1** [comment]
@ydem I never meant it turn into nicehash being able to blame Dillion for their servers being down and ddos protection going wacky.

@DillionN I'll look again and update ad necessary, I remember seeing it

**Comment by ydem** [comment]
@DillonN  lol, but i like your version, i don't care about temp bans, i just change ip and problem solved, i'd rather have a better optimized version using better algos then an official one until it gets everything implemented, that's just my own point of view of course...
Cheers and keep up the great work.

**Comment by DillonN** [comment]
@ydem I share your point of view, but if NH does ask me to take the repo down I'll have to. After all it is their software and the main repo is not under any license that explicitly allows people to distribute their own version. 

Hopefully they find that my version isn't doing any harm! May actually be doing them good, since better hashrates makes them more money

**Comment by nonotme1** [comment]
@DillonN I can attest to the fact that I went from 170 sol/s on the official to about 260 sol/s on your version. 

My bad man.

**Comment by DillonN** [comment]
@nonotme1 Don't worry about it, this version has gotten pretty popular and it was only a matter of time before NH took notice of it

**Comment by DillonN** [comment]
Looks like people are seeing these problems with even the official NHM so pretty sure it's not a problem on my end

**Comment by CreamyG31337** [comment]
Thanks for fixing it so quickly. You are doing a lot better job of handling the situation that Nicehash. Ignoring support tickets, telling us not download your release and suggesting it may have a virus is laughable. Please keep up the good work. Hopefully, when they adopt your changes they remember to give you some credit and an apology. I think they're just butthurt they aren't getting their 50 cents of benchmarking profits now.

**Comment by nicehashdev** [comment]
@DillonN We don't mind you making fork of NHM. The only thing we don't like is that you continued versioning it as if it came from us.

Now, regarding this ban issue. That is just unfortunate coincidence, because it conflicts with our anti-botnet protection. Without this protection, NH would be full of botnet miners like minergate is. We take botnet mining very seriously and ban/block as much as possible. However, they still come back somehow. We did not do anything to intentionally block @DillonN 's version of NHM.

We fully understand "the need" for faster speeds and profits. Which is okay, if you are an existing miner and you are well aware of AV-tagging situation. A closed source devfee miner is usually detected by AVs as being a well known trojan or keylogger. Miners know that this usually isn't true, or they run this on a special PC that has nothing but mining operation going on.

But our goals are beyond reaching **existing** miners. With NHM, we are trying to reach all the potential miners. And believe us, these potential miners quickly freak out, when they see money making software being riddled with trojan horses and keyloggers. That is simply a no go for them and they immediatelly think: "ah, that is just some malware! it would be too good if that was trully making me money". Try to understand our point of view here.

We are taking all the steps neccessary to have (one day in the future) fully UNDETECTED NHM version, using only software that we have developed and that we can proove it isn't a trojan horse, virus or keylogger. Therefore, we cannot use existing closed source miners. We are developing our own (excavator), and we have decided that if our version is slightly underperforming, we will still use it rather than closed source miner from an unknown anonymous person, as that overweights the problems AV detected software brings. In the near future, we will also remove claymore miners, ethminer, ccminer and sgminer.

Once our NHM is fully ours, we will also launch lawsuits if neccessary against AV companies for false tagging our application. Until we rely on closed source software by unknown person, of course, we cannot do that and this hurts our business.

As for the thing with @DillonN ; I have sent you PM on reddit about your skype, please, respond to me, I would like to talk to you. Thank you!

**Comment by CreamyG31337** [comment]
@nicehashdev thanks for being reasonable. I agree that the versioning should not be similar. Some of us enjoy squeezing every penny of profit from the miners so I'm grateful for this version that gives me a few new options. It might be too much for some people, but there's plenty of room to explain things to the noobs on Reddit that should probably not mess around with this or any modified versions. I just take exception to the generic statements like "never download unofficial versions" because we don't know if you're trying to protect us or we're actually causing some problem or what.
Anyways, now that the banning situation is cleared up, I hope your official devs take a look at some of the code changes done in this fork and consider merging them into 2.x or another 1.x update. There's a lot here besides Nvida dual mining.
