### ISSUE TITLE
gtx 10XX p0 state

### ISSUE THREAD

**Issue by 008** [DillonN/NiceHashMiner#19]
Hi,
i know you have gtx1080, do you have P0 state ?

cmd
cd C:\Program Files\NVIDIA Corporation\NVSMI\
nvidia-smi -q -d PERFORMANCE

i have only P2 state

the problem maybe in drivers?
this one makes N/A in the clocks  "nvidia-smi -q -d SUPPORTED_CLOCKS"

(nvidiasetp0state.exe with admin rights dosnt helps)

**Comment by ramius86** [comment]
got same problem but it's not releated with this nhm version

**Comment by DillonN** [comment]
Hey, I have 1080 Tis but it seems the P states have changed quite a bit with Pascal compared to older gens (probably for GPU boost 3.0). I do not claim to know too much about CUDA programming but it seems my primary card is always at P0 (probably since I have dual monitors and NVIDIA locks at high performance for that) and the second card goes from P8 to P2 when starting to mine. 

Even when using a tool like NVIDIA Inspector, forcing P0 on the second card will only give me P2. So, from what I can tell the only way to force P0 is to have multiple monitors hooked up to the GPU. That being said GPU Boost 3.0 is pretty smart and my second GPU at P2 gets the same or better performance than the first GPU at P0 (better when the first GPU gets hotter and drops clocks a bit)

**Comment by 008** [comment]
can you see hash diference in P2 and P0 ?

**Comment by DillonN** [comment]
There is no discernible difference from what I can tell
